package com.jobsite.data;

import com.jobsite.security.Passwords;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.math.BigDecimal;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class Database {
    private static final Pattern PRICE_PATTERN = Pattern.compile("(\\d[\\d,]*(?:\\.\\d{1,2})?)");
    private static final String URL = System.getenv().getOrDefault(
            "DB_URL",
            "jdbc:h2:file:./data/jobsite;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE"
    );
    private static final String USER = System.getenv().getOrDefault("DB_USER", "sa");
    private static final String PASSWORD = System.getenv().getOrDefault("DB_PASSWORD", "");

    private Database() {
    }

    public static Connection connection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    public static void initialize() {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table if not exists users (
                        id bigint generated by default as identity primary key,
                        name varchar(120) not null,
                        email varchar(180) not null unique,
                        password_hash varchar(255) not null,
                        role varchar(30) not null,
                        company_name varchar(160),
                        company_email varchar(180),
                        approved boolean not null default false,
                        active boolean not null default true,
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    merge into users key(email) values (
                        1,
                        'System Administrator',
                        'admin@example.com',
                        '%s',
                        'ADMIN',
                        null,
                        null,
                        true,
                        true,
                        current_timestamp
                    )
                    """.formatted(Passwords.hash("admin123")));

            statement.execute("""
                    create table if not exists jobs (
                        id bigint generated by default as identity primary key,
                        employer_id bigint not null references users(id),
                        title varchar(180) not null,
                        location varchar(160) not null,
                        job_type varchar(40) not null,
                        salary varchar(80),
                        price numeric(15, 2),
                        description clob not null,
                        requirements clob,
                        status varchar(30) not null default 'OPEN',
                        created_at timestamp not null default current_timestamp
                    )
                    """);
            statement.execute("alter table jobs add column if not exists price numeric(15, 2)");
            migrateJobPrices(connection);

            statement.execute("""
                    create table if not exists job_skills (
                        job_id bigint not null references jobs(id) on delete cascade,
                        skill varchar(80) not null,
                        primary key (job_id, skill)
                    )
                    """);

            statement.execute("""
                    create table if not exists applications (
                        id bigint generated by default as identity primary key,
                        job_id bigint not null references jobs(id) on delete cascade,
                        seeker_id bigint not null references users(id),
                        cover_letter clob,
                        status varchar(30) not null default 'SUBMITTED',
                        created_at timestamp not null default current_timestamp,
                        unique(job_id, seeker_id)
                    )
                    """);

            statement.execute("""
                    create table if not exists financial_transactions (
                        id bigint generated by default as identity primary key,
                        application_id bigint references applications(id) on delete set null,
                        employer_id bigint references users(id),
                        seeker_id bigint not null references users(id),
                        type varchar(30) not null,
                        amount numeric(15, 2) not null,
                        note varchar(500),
                        payout_method varchar(60),
                        payout_account varchar(180),
                        status varchar(30) not null default 'COMPLETED',
                        created_at timestamp not null default current_timestamp
                    )
                    """);
            statement.execute("""
                    create unique index if not exists uq_completed_job_payment
                    on financial_transactions(application_id, type)
                    """);

            statement.execute("""
                    create table if not exists cv_profiles (
                        seeker_id bigint primary key references users(id) on delete cascade,
                        headline varchar(180),
                        summary clob,
                        skills clob,
                        experience clob,
                        education clob,
                        file_name varchar(255),
                        file_path varchar(500),
                        updated_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    create table if not exists job_alerts (
                        id bigint generated by default as identity primary key,
                        seeker_id bigint not null references users(id) on delete cascade,
                        keyword varchar(180),
                        location varchar(160),
                        job_type varchar(40),
                        active boolean not null default true,
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    create table if not exists cv_templates (
                        id bigint generated by default as identity primary key,
                        name varchar(120) not null,
                        body clob not null,
                        active boolean not null default true,
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    merge into cv_templates key(id) values (
                        1,
                        'Professional',
                        'Name: {{name}}\\nHeadline: {{headline}}\\nSummary: {{summary}}\\nSkills: {{skills}}\\nExperience: {{experience}}\\nEducation: {{education}}',
                        true,
                        current_timestamp
                    )
                    """);
        } catch (SQLException exception) {
            throw new IllegalStateException("Unable to initialize database", exception);
        }
    }

    private static void migrateJobPrices(Connection connection) throws SQLException {
        try (PreparedStatement select = connection.prepareStatement(
                "select id, salary from jobs where price is null and salary is not null"
        ); ResultSet resultSet = select.executeQuery();
             PreparedStatement update = connection.prepareStatement("update jobs set price = ? where id = ?")) {
            while (resultSet.next()) {
                BigDecimal price = parsePrice(resultSet.getString("salary"));
                if (price != null) {
                    update.setBigDecimal(1, price);
                    update.setLong(2, resultSet.getLong("id"));
                    update.addBatch();
                }
            }
            update.executeBatch();
        }
    }

    private static BigDecimal parsePrice(String value) {
        if (value == null) {
            return null;
        }
        Matcher matcher = PRICE_PATTERN.matcher(value);
        if (!matcher.find()) {
            return null;
        }
        try {
            return new BigDecimal(matcher.group(1).replace(",", ""));
        } catch (NumberFormatException exception) {
            return null;
        }
    }
}
