package com.jobsite.data;

import com.jobsite.security.Passwords;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public final class Database {
    private static final String URL = System.getenv().getOrDefault(
            "DB_URL",
            "jdbc:h2:file:./data/jobsite;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE"
    );
    private static final String USER = System.getenv().getOrDefault("DB_USER", "sa");
    private static final String PASSWORD = System.getenv().getOrDefault("DB_PASSWORD", "");

    private Database() {
    }

    public static Connection connection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    public static void initialize() {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table if not exists users (
                        id bigint generated by default as identity primary key,
                        name varchar(120) not null,
                        email varchar(180) not null unique,
                        password_hash varchar(255) not null,
                        role varchar(30) not null,
                        company_name varchar(160),
                        company_email varchar(180),
                        approved boolean not null default false,
                        active boolean not null default true,
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    merge into users key(email) values (
                        1,
                        'System Administrator',
                        'admin@example.com',
                        '%s',
                        'ADMIN',
                        null,
                        null,
                        true,
                        true,
                        current_timestamp
                    )
                    """.formatted(Passwords.hash("admin123")));

            statement.execute("""
                    create table if not exists jobs (
                        id bigint generated by default as identity primary key,
                        employer_id bigint not null references users(id),
                        title varchar(180) not null,
                        location varchar(160) not null,
                        job_type varchar(40) not null,
                        salary varchar(80),
                        description clob not null,
                        requirements clob,
                        status varchar(30) not null default 'OPEN',
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    create table if not exists applications (
                        id bigint generated by default as identity primary key,
                        job_id bigint not null references jobs(id) on delete cascade,
                        seeker_id bigint not null references users(id),
                        cover_letter clob,
                        status varchar(30) not null default 'SUBMITTED',
                        created_at timestamp not null default current_timestamp,
                        unique(job_id, seeker_id)
                    )
                    """);

            statement.execute("""
                    create table if not exists cv_profiles (
                        seeker_id bigint primary key references users(id) on delete cascade,
                        headline varchar(180),
                        summary clob,
                        skills clob,
                        experience clob,
                        education clob,
                        file_name varchar(255),
                        file_path varchar(500),
                        updated_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    create table if not exists job_alerts (
                        id bigint generated by default as identity primary key,
                        seeker_id bigint not null references users(id) on delete cascade,
                        keyword varchar(180),
                        location varchar(160),
                        job_type varchar(40),
                        active boolean not null default true,
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    create table if not exists cv_templates (
                        id bigint generated by default as identity primary key,
                        name varchar(120) not null,
                        body clob not null,
                        active boolean not null default true,
                        created_at timestamp not null default current_timestamp
                    )
                    """);

            statement.execute("""
                    merge into cv_templates key(id) values (
                        1,
                        'Professional',
                        'Name: {{name}}\\nHeadline: {{headline}}\\nSummary: {{summary}}\\nSkills: {{skills}}\\nExperience: {{experience}}\\nEducation: {{education}}',
                        true,
                        current_timestamp
                    )
                    """);
        } catch (SQLException exception) {
            throw new IllegalStateException("Unable to initialize database", exception);
        }
    }
}
